// MailSettings table columns configuration (eski Mail Ayarları grid ile uyumlu)
import { TableColumn, ColumnType } from 'src/app/components/data-table/data-table.component';

export const tableColumns: TableColumn[] = [
  {
    field: 'ID',
    label: 'ID',
    text: 'ID',
    type: 'int' as ColumnType,
    sortable: true,
    width: '60px',
    size: '60px',
    min: 20,
    searchable: 'int',
    resizable: true
  },
  {
    field: 'Name',
    label: 'Adı',
    text: 'Adı',
    type: 'text' as ColumnType,
    sortable: true,
    width: '120px',
    size: '120px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'UserName',
    label: 'Kullanıcı Adı',
    text: 'Kullanıcı Adı',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'UserPass',
    label: 'Şifre',
    text: 'Şifre',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'CustomerCode',
    label: 'Müşteri Kodu',
    text: 'Müşteri Kodu',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'ApiKey',
    label: 'ApiKey',
    text: 'ApiKey',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'VendorCode',
    label: 'Vendor Kodu',
    text: 'Vendor Kodu',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'OriginatorId',
    label: 'Originator',
    text: 'Originator',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'TemplateId',
    label: 'Template',
    text: 'Template',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'Protocol',
    label: 'Protokol',
    text: 'Protokol',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'SMTPHost',
    label: 'Host',
    text: 'Host',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'SMTPUser',
    label: 'Kullanıcı',
    text: 'Kullanıcı',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'SMTPPass',
    label: 'Şifre',
    text: 'Şifre',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'SMTPPort',
    label: 'Port',
    text: 'Port',
    type: 'int' as ColumnType,
    sortable: true,
    width: '60px',
    size: '60px',
    min: 20,
    searchable: 'int',
    resizable: true
  },
  {
    field: 'SMTPCrypto',
    label: 'Crypto',
    text: 'Crypto',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'MailType',
    label: 'Mail Tipi',
    text: 'Mail Tipi',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'Charset',
    label: 'Karakter Seti',
    text: 'Karakter Seti',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'FromMail',
    label: 'Gönderen Mail',
    text: 'Gönderen Mail',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  },
  {
    field: 'FromName',
    label: 'Gönderen Adı',
    text: 'Gönderen Adı',
    type: 'text' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'text',
    resizable: true
  }
];
