// TaskSchedulers table columns configuration
import { TableColumn, ColumnType } from 'src/app/components/data-table/data-table.component';

export const tableColumns: TableColumn[] = [
  {
    field: 'Id',
    label: 'ID',
    text: 'ID',
    type: 'int' as ColumnType,
    sortable: true,
    width: '60px',
    size: '60px',
    min: 20,
    searchable: 'int' as ColumnType,
    resizable: true,
    align: 'right',
  },
  {
    field: 'Name',
    label: 'Adı',
    text: 'Adı',
    type: 'text' as ColumnType,
    sortable: true,
    width: '160px',
    size: '160px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'Type',
    label: 'Tipi',
    text: 'Tipi',
    type: 'text' as ColumnType,
    sortable: true,
    width: '120px',
    size: '120px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'SntpServer',
    label: 'SntpServer',
    text: 'SntpServer',
    type: 'text' as ColumnType,
    sortable: true,
    width: '140px',
    size: '140px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'EventTime',
    label: 'İşlem Saati',
    text: 'İşlem Saati',
    type: 'time' as ColumnType,
    sortable: true,
    width: '140px',
    size: '140px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'StartDate',
    label: 'Başlangıç Tarihi',
    text: 'Başlangıç Tarihi',
    type: 'date' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'date' as ColumnType,
    resizable: true,
  },
  {
    field: 'EndDate',
    label: 'Bitiş Tarihi',
    text: 'Bitiş Tarihi',
    type: 'date' as ColumnType,
    sortable: true,
    width: '150px',
    size: '150px',
    min: 20,
    searchable: 'date' as ColumnType,
    resizable: true,
  },
  {
    field: 'PlaceId',
    label: 'Bölge Adı',
    text: 'Bölge Adı',
    type: 'int' as ColumnType,
    sortable: true,
    width: '120px',
    size: '120px',
    min: 20,
    searchable: 'int' as ColumnType,
    resizable: true,
    align: 'right',
  },
  {
    field: 'AccessZoneId',
    label: 'Bölge',
    text: 'Bölge',
    type: 'int' as ColumnType,
    sortable: true,
    width: '120px',
    size: '120px',
    min: 20,
    searchable: 'int' as ColumnType,
    resizable: true,
    align: 'right',
  },
  {
    field: 'DayOfWeek',
    label: 'Haftanın Günü',
    text: 'Haftanın Günü',
    type: 'int' as ColumnType,
    sortable: true,
    width: '120px',
    size: '120px',
    min: 20,
    searchable: 'int' as ColumnType,
    resizable: true,
    align: 'right',
  },
  {
    field: 'ServerIpAddressFirmwareUpdate',
    label: 'Firmware Server',
    text: 'Firmware Server',
    type: 'text' as ColumnType,
    sortable: true,
    width: '160px',
    size: '160px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'SubscriptionPass',
    label: 'Abone Geçiş',
    text: 'Abone Geçiş',
    type: 'checkbox' as ColumnType,
    sortable: true,
    width: '110px',
    size: '110px',
    min: 20,
    searchable: 'checkbox' as ColumnType,
    resizable: true,
    align: 'center',
  },
  {
    field: 'Url',
    label: 'Url',
    text: 'Url',
    type: 'text' as ColumnType,
    sortable: true,
    width: '220px',
    size: '220px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'isFingerPrint',
    label: 'Parmak İzi',
    text: 'Parmak İzi',
    type: 'checkbox' as ColumnType,
    sortable: true,
    width: '110px',
    size: '110px',
    min: 20,
    searchable: 'checkbox' as ColumnType,
    resizable: true,
    align: 'center',
  },
];

