// Report Templates (Reports) table columns configuration
import { TableColumn, ColumnType, TableRow } from 'src/app/components/data-table/data-table.component';

export const tableColumns: TableColumn[] = [
  {
    field: 'Id',
    label: 'ID',
    text: 'ID',
    type: 'int' as ColumnType,
    sortable: true,
    width: '80px',
    size: '80px',
    min: 20,
    searchable: 'int' as ColumnType,
    resizable: true,
    align: 'right',
  },
  {
    field: 'Name',
    label: 'Ad',
    text: 'Ad',
    type: 'text' as ColumnType,
    sortable: true,
    width: '220px',
    size: '220px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'Grid',
    label: 'Grid',
    text: 'Grid',
    type: 'text' as ColumnType,
    sortable: true,
    width: '160px',
    size: '160px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'Logic',
    label: 'Logic',
    text: 'Logic',
    type: 'text' as ColumnType,
    sortable: true,
    width: '90px',
    size: '90px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
    align: 'center',
  },
  {
    field: 'Url',
    label: 'Url',
    text: 'Url',
    type: 'text' as ColumnType,
    sortable: true,
    width: '260px',
    size: '260px',
    min: 20,
    searchable: 'text' as ColumnType,
    resizable: true,
  },
  {
    field: 'Filters',
    label: 'Filtreler',
    text: 'Filtreler',
    type: 'textarea' as ColumnType,
    sortable: false,
    width: '400px',
    size: '400px',
    min: 20,
    searchable: false,
    resizable: true,
    render: (record: TableRow) => {
      const raw = record['Filters'];
      if (raw == null) return '';
      const text = String(raw);
      // Keep grid readable: show a short preview
      return text.length > 160 ? `${text.slice(0, 160)}…` : text;
    },
  },
  {
    field: 'CreatedAt',
    label: 'Oluşturulma',
    text: 'Oluşturulma',
    type: 'datetime' as ColumnType,
    sortable: true,
    width: '170px',
    size: '170px',
    min: 20,
    searchable: 'datetime' as ColumnType,
    resizable: true,
  },
  {
    field: 'UpdatedAt',
    label: 'Güncellenme',
    text: 'Güncellenme',
    type: 'datetime' as ColumnType,
    sortable: true,
    width: '170px',
    size: '170px',
    min: 20,
    searchable: 'datetime' as ColumnType,
    resizable: true,
  },
];

